### ISSUE TITLE
Add the "Transmission Distance" field for HueForge

### ISSUE THREAD

**Issue by mawoka-myblock** [Donkie/Spoolman#235] opened 2023-12-29 19:12 UTC
**Is your feature request related to a problem? Please describe.**
Td values are important when working with HueForge and having all data about my filament in one place would be great.

**Describe the solution you'd like**
A new field like we already have for "Article Number".

**Describe alternatives you've considered**
Not implementing it? Or using the comment section to save it

**Additional context**

**Comment by Donkie** [comment] 2024-01-26 10:22
I have now added the ability to make custom extra fields. Please test it out in the beta for me before I make a release. See #283 for more information.

**Comment by Donkie** [comment] 2024-01-26 10:23
Duplicate of #200

**Closed by Donkie** 2024-01-26 10:23 UTC
Labels: Feature Request
