### ISSUE TITLE
Unraid Permission Error

### ISSUE THREAD

**Issue by leon2908** [Donkie/Spoolman#143] opened 2023-10-09 14:59 UTC
I installed the docker from the Unraid community application site, set up postgresql14 and tried to run it. Unfortunately it didn't work and the logs showed:

**_Traceback (most recent call last):
  File "/home/app/spoolman/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/spoolman/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/app/spoolman/spoolman/main.py", line 21, in <module>
    file_handler = TimedRotatingFileHandler(log_file, when="midnight", backupCount=5)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/handlers.py", line 214, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
  File "/usr/local/lib/python3.11/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/app/.local/share/spoolman/spoolman.log'_**

** Drücke eine BELIEBIGE TASTE, um dieses Fenster zu schließen **

**Comment by MacVille** [comment] 2023-10-10 04:42
I had the same Issue. But i got it Fixed.
Don't use the Default Container Path for the Mapping use only  /data/ 
![image](https://github.com/Donkie/Spoolman/assets/20932457/874617af-b4e8-43d3-a52e-f866e36d45a3)

After that change the Container starts and it's working.

**Comment by Ferdinand99** [comment] 2023-10-10 17:20
> I had the same Issue. But i got it Fixed. Don't use the Default Container Path for the Mapping use only /data/ ![image](https://user-images.githubusercontent.com/20932457/273778780-874617af-b4e8-43d3-a52e-f866e36d45a3.png)
> 
> After that change the Container starts and it's working.

I tried changing it to /data, but I get the same error message as leon2908 with the permission error

**Comment by Ferdinand99** [comment] 2023-10-10 18:20
I can also recommend that if you use mysql, change to MariaDB. I had problems connecting to mysql, but MariaDB worked flawlessly

**Comment by leon2908** [comment] 2023-10-10 23:25
> I had the same Issue. But i got it Fixed. Don't use the Default Container Path for the Mapping use only /data/ ![image](https://user-images.githubusercontent.com/20932457/273778780-874617af-b4e8-43d3-a52e-f866e36d45a3.png)
> 
> After that change the Container starts and it's working.

Thank you very mutch. It worked!

**Comment by m-klecka** [comment] 2023-10-13 18:58
I made that template. I'll change it so it fefaults to /data :)

**Comment by Fribb** [comment] 2023-11-25 06:54
@leon2908 @Donkie 

Is that really a solution though? Yes, the container is now spinning up and not crashing right from the start but changing the container path to `/data` means that the log file is not being created in the AppData directory. This means that the log file is only being stored in the docker container. If there is no log rotation being applied here then this log file would fill up over time eating more and more space.

And since in Unraid you are limited to the set Docker Image size in your Docker settings, this could mean that your Docker image is slowly but surely running full.

With `/home/app/.local/share/spoolman` it works as intended if you use `chown 1000:1000 /mnt/user/appdata/spoolman` prior to starting the container. 

I am not sure how or where the SQLite DB is being stored, since I use my Postgres instance, but if it is or should be stored in the same location, the same applies to it with a more severe consequence, the next time the container updates your database is gone.

**Comment by Donkie** [comment] 2023-11-25 10:04
I didn't really look into the solution here in detail before I closed it. I'm not the maintainer of the unraid plugin. But yes, you're right @Fribb , the /data folder fix is useless, nothing is stored in there. Both the SQLite DB and the logs are stored in /home/app/.local/share/spoolman.

@m-klecka this needs to be resolved in the unraid plugin immediately

**Comment by Fribb** [comment] 2023-11-25 10:07
I just set it up today and it still has the `/home/app/.local/share/spoolman` as default in the template.

**Comment by m-klecka** [comment] 2023-11-25 12:27
> I didn't really look into the solution here in detail before I closed it. I'm not the maintainer of the unraid plugin. But yes, you're right @Fribb , the /data folder fix is useless, nothing is stored in there. Both the SQLite DB and the logs are stored in /home/app/.local/share/spoolman.
> 
> @m-klecka this needs to be resolved in the unraid plugin immediately

I don't think I can do anything. The unraid template is basically a docker run with parameters from your docker image. Problem is, unraid gets UMASK values from the container but uses nobody:users user and group for default user. And as far as I know there's no way to change that when creating the container. If I manually change permissions for the mapped folder in unraid to drwxr-xrwx it works as expected. But i don't really understand this that much, so I can be mistaken. If so, and someone has a different fix, tell me please:)

**Comment by Donkie** [comment] 2023-11-25 15:36
The permissions is an issue yes, but it's wrong that you have it set to /data as the container path, since that path is useless. It should be reverted back to `/home/app/.local/share/spoolman`

**Comment by m-klecka** [comment] 2023-11-25 15:37
In the template I reverted it back to the original path you specify. So new containers in unraid get created with your original path

**Comment by Fribb** [comment] 2023-11-25 16:01
> In the template I reverted it back to the original path you specify. So new containers in unraid get created with your original path

It might be good to add that to the description of the Template, that you have to set the ownership to 1000:1000 (instead of 99:100 in unraid) so that new users might not need to go through the trouble searching for the issue when they, hopefully, read that description.

**Comment by Donkie** [comment] 2023-12-17 18:47
With 0.14 I hope these permission issues are alleviated. #204 is also in the pipeline to improve the situation.

Please re-open if permissions are still a bugger.

**Closed by Donkie** 2023-12-17 18:47 UTC
Labels: Bug
