### ISSUE TITLE
Support for multiple colors for coextrusion filaments

### ISSUE THREAD

**Issue by jerome1232** [Donkie/Spoolman#209] opened 2023-12-01 18:37 UTC
Some filaments have co-extrusion up to three colors, it would be fantastic to be able to select up to three colors for a filament to accurately reflect the color of the spool

**Comment by Donkie** [comment] 2023-12-19 18:51
Duplicate of https://github.com/Donkie/Spoolman/issues/144

**Closed by Donkie** 2023-12-19 18:51 UTC
